### ISSUE TITLE
CA cert for TLS authentication 

### ISSUE THREAD

**Issue by nezlis** [fstab/grok_exporter#117]
Hey there, hope you are doing well.

Is it possible to add CA cert for client authentication?
node_exporter already  has that feature and it will be awesome to add it to your project.

Thank you!

**Comment by fstab** [comment]
It's not yet possible, but it should be easy to implement. I'll have a look.

**Comment by fstab** [comment]
I started a feature branch [client_ca](https://github.com/fstab/grok_exporter/tree/client_ca), but didn't find the time to test it yet. It should allow you to add the following to the `server` configuration:
```
client_ca: /path/to/client_ca/file
client_auth: RequireAndVerifyClientCert
```
Behavior should be the same as in `node_exporter`.

**Comment by fstab** [comment]
I tested it and added documentation: [https://github.com/fstab/grok_exporter/blob/client_ca/CONFIG.md#server-section](https://github.com/fstab/grok_exporter/blob/client_ca/CONFIG.md#server-section).
I'll keep it in the feature branch until the next release, because documentation should only be merged when the feature is released.

**Comment by nezlis** [comment]
Thank you, everything working as expected!
