### ISSUE TITLE
Grok detects when pattern appears but not when it disappears

### ISSUE THREAD

**Issue by koen-serneels** [fstab/grok_exporter#148]
We have a (special) log file per module which is cleared on restart. Grok is configured to look for a specific pattern in those files. From the moment a module starts and the pattern appears, grok flags it, good. However, if after a restart the pattern is no longer there, grok fails somehow to refresh itself and still indicates the existence of the pattern. We've tried setting `readall: true` to no avail. The weird thing is that the detection always works when the pattern shows up, but it doesn't detect when it goes away. The flow is always the same; module (re)starts, a log file is written, log file contains the pattern or not. Grok is running in docker (latest) and the modules producing the log file are also running in containers, the log files are bind mounted. We have now tried to set the poll interval to see if this might solve the case (which seems unlikely as grok seems to detect changes when the pattern appears...). Is there somewhere a log file or other means how we can debug this behavior?

**Comment by fstab** [comment]
Hi Koen, usually users do not want a metric to disappear if the logfile becomes empty. A typical example is a metric counting the number of `ERROR` messages. After a while, `logrotate` might rename the current log file, and the application continues logging to a new empty file. However, in that case users would not expect the `ERROR` counter to reset to zero. Rather, the counter should remain as it is and increase when the next `ERROR` is logged.

That being said, there is a `retention` configuration for metrics where you can configure that metrics expire after some time if the pattern is not seen again. So if you configure `retention` to `1h`, the metric will disappear after `1h` if there was no more matching log line. Note that if you set `retention` to a value lower than `1m` (1 minute), you also need to configure the `retention_check_interval` because by default retention is only checked every `53s` (53 seconds).

**Comment by koen-serneels** [comment]
This seems to have solved it, thanks for explaining.
