### ISSUE TITLE
Grok Exporter multiple logfiles branch fails if log files do not exist

### ISSUE THREAD

**Issue by cholmes11** [fstab/grok_exporter#40]
This is a similar issue to issue #23. The changes in #23 only seem to be on the master branch. Would it require much effort to get this on the multiple_logfiles branch? I have no experience with the go language.

**Comment by fstab** [comment]
The _multiple_logfiles_ branch is pretty outdated. I think the best approach would be to throw the branch away and start again from the current master.

I am aware that support for multiple logfiles is the most requested feature and I hope I will find the time to implement it soon. As of now I think the best option is to start one `grok_exporter` instance for each logfile instead of using the _multiple_logfiles_ branch.

**Comment by muzammil360** [comment]
@fstab, when you say **start one grok_exporter instance for each logfile**, what do you exactly mean?
1. completely new folder (with identical build)
2. same folder but use duplicate binary with new config file (other files will be shared)
3. exactly one build but run same binary with two different config files (each targeting a particular log file) in two terminal windows. 

Sorry, if its a silly questions.

**Comment by fstab** [comment]
`3` is what I meant.

**Comment by fstab** [comment]
Multiple file support is now supported with release 1.0.0.RC1. Configuration is described in [CONFIG.md](https://github.com/fstab/grok_exporter/blob/master/CONFIG.md).
