### ISSUE TITLE
support newer version of Oniguruma

### ISSUE THREAD

**Issue by williamh** [fstab/grok_exporter#51]
Hello, I am a packager for Gentoo linux.

I have been asked to look into packaging this and making it available to our users.

I see from your README.md that that you require oniguruma 5.9.6; however, that version is not available in Gentoo. We have versions 6.8.2, 6.9.0 and 6.9.1.

What are your plans for updating this? Do you have any idea when you will support a newer version?

Thanks much.

**Comment by fstab** [comment]
Good news: All issues with Oniguruma 6 seem to be fixed, `grok_exporter` runs out-of-the-box with Oniguruma 6 without any code change. You can build a package based on `grok_exporter` tag `v0.2.6` and simply use Oniguruma 6 instead of 5.9.6. There should be no relevant difference between 6.8.2, 6.9.0 or 6.9.1.
