### ISSUE TITLE
Tailer is not streaming line if file is a symbolic link 

### ISSUE THREAD

**Issue by dbenque** [fstab/grok_exporter#52]
Hi,

Seems like the Tailer is not pushing lines over the channel ( Lines() ) when the given filepath is a symbolic link.

I am instanciating the tailer this way:
`logtailer := tailer.RunFseventFileTailer(filepath, false, true, logger)`

the filepath is pointing to the file named **access.log** that is a symbolic link
```
-rw-r--r-- 1 dbenque dbenque  521 Feb 20 23:38 access0
lrwxrwxrwx 1 dbenque dbenque    7 Feb 20 23:38 access.log -> access0
```

At the same time I have process writting inside file **access0**. The lines finally arrive in one bulk when the process writting to the file **access0** is terminated.

Would it be possible to support Symbolic Link for the tailer?

Note:
```
> uname -a
Linux ncelrnd0228 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks,
David

**Comment by fstab** [comment]
The file tailer implementation doesn't support symbolic links. The reason is that the implementation reacts on file system events, like _some process wrote to the file_. With the symbolic link, these events don't occur because technically you don't write the symbolic link, but you write the file it points to.

Of course it would be possible to implement that (when the tailer sees a symbolic link, it could watch the file it points to instead of the link itselv), but this is currently not on the todo list.

The best workaround is to use the polling tailer instead. In `grok_exporter` you get that by configuring `poll_interval_seconds`, in code you get it with `tailer.RunPollingFileTailer(...)` or the new `fswatcher.RunPollingFileTailer(...)`. I am currently refactoring the tailer implementations to add support for multiple log files, so if you use this in code be aware that this is internal api and will change in the near future.
