### ISSUE TITLE
Only parse/calculate the last line/match?

### ISSUE THREAD

**Issue by valdisrigdon** [fstab/grok_exporter#6]
Would it be possible to configure the grok section to only create metrics for the last matched line? I am trying to grok CSV files but each line already contains the aggregate result.

**Comment by fstab** [comment]
So far, `grok_exporter` used to measure the sum of all observed values for `gauge` values. But reading your question I concluded the current implementation does not really make sense. So I changed the implementation, so that `gauge` metrics measure the last observed value by default. I also introduced an optional configuration `cumulative` that can be used to go back to the previous behaviour. I committed the changes so the new behaviour is implemented if you build `grok_exporter` from source. I will review the changes tomorrow and if everything looks fine, I will build a release with the new behaviour. Thanks for your question.

**Comment by valdisrigdon** [comment]
This is exactly what I was looking for! Thanks!

**Comment by fstab** [comment]
Just published rel 0.1.3 with the new gauge behaviour.
