### ISSUE TITLE
Fail on missing directory

### ISSUE THREAD

**Issue by matjaz99** [fstab/grok_exporter#81]
Hello

Grok exporter fails to start if there is no directory where it expects to find log files. I have set the flag `fail_on_missing_logfile: false`. This flag seems to have effect on files, but not on directories, although I think it is the same situation - there is no log file.

My applications run in Docker and I cannot know on which server the container will actually be deployed. Now I need to maintain several config files and I need to know exactly on which servers should I put the correct config file. I would like to have one config file for all servers.

I am running grok-exporter v1.0.0.RC3 on CentOS 7. The error I get is this:

```
Feb 28 11:47:06 node-1 grok_exporter[18321]: Starting server on http://node-1:9144/metrics
Feb 28 11:47:06 node-1 grok_exporter[18321]: error reading log lines: "/var/log/my-app": no such directory
Feb 28 11:47:06 node-1 systemd[1]: grok_exporter.service: main process exited, code=exited, status=255/n/a
Feb 28 11:47:06 node-1 systemd[1]: Unit grok_exporter.service entered failed state.
Feb 28 11:47:06 node-1 systemd[1]: grok_exporter.service failed.
```

Thanks.
Matjaž

**Comment by fstab** [comment]
Hello Matjaž,

this is a limitation of the current implementation. `grok_exporter` assumes that the directory containing log files is present, so that it can watch the directory in order to be notified when logfiles are created, moved, deleted. If the directory is not found, `grok_exporter` will terminate.

If the directory depends on the server where the Docker container is deployed, a workaround might be to write a start script to create the `grok_exporter` config dynamically when the Docker container starts up. Maybe something like the following:

```bash
#!/bin/bash

set -e

LOGDIR="/var/log/$(hostname)"

cat <<EOF > ./config.yaml
global:
    config_version: 3
input:
    type: file
    path: $LOGDIR/example.log
    readall: true
metrics:
    - type: counter
      name: errors_total
      help: number of ERRORs in the log file.
      match: ERROR
EOF

exec grok_exporter -config ./config.yaml
```
It's not ideal, but at least it saves you from maintaining several config files.

**Comment by matjaz99** [comment]
I agree, workaround with script will do the trick. Nevertheless, I noticed that `grok_exporter` will also terminate if I remove the directory while running (eg. uninstall app), and I have to reconfigure and restart it again, which makes it a bit inconvenient for me.

BTW, is environment variable substitution supported in config.yml?

BR, Matjaž

**Comment by fstab** [comment]
No, there is no variable substitution for `config.yml` built into `grok_exporter`, but it can easily be done with an external tool like a small shell script.

It's correct that if the log directory is removed, `grok_exporter` will terminate. The best thing you can do is to find a way to automate reconfiguration and restart, so that you don't need to do that manually if that happens.

**Comment by matjaz99** [comment]
Thanks. I'll close the issue, although I still think it would be a beneficial improvement regarding stability and robustness.
Anyway, I like your project and keep on the good work :)
